version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: mydb
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shareit-server
    restart: always
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING.DATASOURCE.DRIVER-CLASS-NAME=org.postgresql.Driver
      - TZ=Europe/Moscow
      - JAVA_OPTS=-Duser.timezone=Europe/Moscow

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: shareit-gateway
    restart: always
    environment:
      TZ: Europe/Moscow
    depends_on:
      - server
    ports:
      - "8080:8080"

volumes:
  postgres_data: